### ISSUE TITLE
Installation / Documentation

### ISSUE THREAD

**Issue by keir-ru** [pluginsGLPI/openvas#4]
Hello. Many thanks for plugin!
I have a questions about information in README file:
"Copy the plugin folder into your glpi/plugins directory. The folder must be named 'prelude' otherwise GLPI framework will fail to initialize the plugin."
If folder has name 'prelude' GLPI doesn't display this plugin in list. If folder has name 'openvas' - everything is ok.

**Comment by wawax** [comment]
Hi,

You're absolutely right. A copy/paste of the prelude plugin's README and I forget to change the name.

I've just fixed it here : https://github.com/pluginsGLPI/openvas/commit/53b177327a5d9dda41a7463fd5a2f9d8e8114a3c
