### ISSUE TITLE
Rules for OpenVAS vulnerabilities

### ISSUE THREAD

**Issue by jswytka** [pluginsGLPI/openvas#6]
No such itens on rules for openvas.

Glpi version 9.1.1
Plugin version: 1.0.1

![image](https://cloud.githubusercontent.com/assets/21204053/21588809/707c8058-d0d1-11e6-82c2-4b737cb453ec.png)

**Comment by wawax** [comment]
Hello,

You don't have the possiblity to create a new rule using the small "+" icon ?
